title:            'Copperfield Annotation Admin'
description:      ''
url:              ''
baseurl:          '/copperfield_annotation_admin'
copyright:        ''
theme:            minima
permalink:        'pretty'
safe:             true
exclude:          [Gemfile*, Rakefile, vendor, spec, README.md]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
