title:            'Copperfield Annotation Admin'
description:      ''
url:              ''
baseurl:          ''
copyright:        ''
theme:      minima
permalink:  'pretty'
safe:       true
exclude:    [Gemfile*, Rakefile, vendor, spec, README.md, wax_theme]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
